name: randnum workflow

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.release.tag_name }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kixco/randnum:${{ github.event.release.tag_name }}

      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Name: Nicolette Lee\nMatriculation: ${{ secrets.MATRICULATION }}\nEmail: ${{ secrets.EMAIL }}\nRepo: git://github.com:niclkw/randnum.git \nImage Name: kixco/randnum:${{ github.event.release.tag_name }}\nImage Url: https://hub.docker.com/repository/docker/kixco/randnum \n"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK